// Integration tests for `aef dev`: shipped skills land as rendered files, dev skills
// as live symlinks, and name collisions keep the dev symlink.
import { mkdtempSync, readFileSync, writeFileSync, existsSync, rmSync, mkdirSync, lstatSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test, expect, describe, beforeAll, afterAll } from 'vitest'
import { runDev } from '../src/cli/commands/dev.js'

const ROOT = process.cwd()

// Run against the real framework root — idempotent since session-start already ran it.
describe('runDev against real framework root', () => {
  test('dev skills are installed as symlinks', () => {
    runDev(ROOT)
    const skillsDir = join(ROOT, '.claude', 'skills')
    // adapter-creator and triage-feedback are the known dev skills
    for (const name of ['adapter-creator', 'triage-feedback']) {
      const entry = join(skillsDir, name)
      expect(existsSync(entry), `${name} should exist`).toBe(true)
      expect(lstatSync(entry).isSymbolicLink(), `${name} should be a symlink`).toBe(true)
    }
  })

  test('shipped skills are installed as rendered files (not symlinks)', () => {
    runDev(ROOT)
    const skillsDir = join(ROOT, '.claude', 'skills')
    // skill-creator is a core-tier shipped skill with no slots
    const entry = join(skillsDir, 'skill-creator')
    expect(existsSync(entry), 'skill-creator should exist').toBe(true)
    expect(lstatSync(entry).isSymbolicLink(), 'skill-creator should not be a symlink').toBe(false)
    expect(lstatSync(entry).isDirectory(), 'skill-creator should be a directory').toBe(true)
    const md = readFileSync(join(entry, 'SKILL.md'), 'utf8')
    expect(md.startsWith('<!-- generated by aef render')).toBe(true)
  })

  test('improve-framework (framework tier) is installed', () => {
    runDev(ROOT)
    const entry = join(ROOT, '.claude', 'skills', 'improve-framework')
    expect(existsSync(entry)).toBe(true)
    expect(lstatSync(entry).isSymbolicLink()).toBe(false)
  })

  test('orm-gated skills are not installed (no orm in dev config)', () => {
    runDev(ROOT)
    const skillsDir = join(ROOT, '.claude', 'skills')
    for (const name of ['migrate-orm', 'data-model-design']) {
      expect(existsSync(join(skillsDir, name)), `${name} should be absent`).toBe(false)
    }
  })
})

describe('runDev name collision: dev skill takes priority over same-named shipped skill', () => {
  let tmp: string

  beforeAll(() => {
    tmp = mkdtempSync(join(tmpdir(), 'agentic-dev-'))
    // Minimal framework structure: one harness, one dev skill, one shipped skill with the same name
    mkdirSync(join(tmp, 'adapters', 'harness', 'test-harness'), { recursive: true })
    writeFileSync(
      join(tmp, 'adapters', 'harness', 'test-harness', 'adapter.json'),
      JSON.stringify({ name: 'test-harness', axis: 'harness', skillsDir: '.test/skills' }),
    )
    mkdirSync(join(tmp, 'dev', 'skills', 'skill-creator'), { recursive: true })
    writeFileSync(join(tmp, 'dev', 'skills', 'skill-creator', 'SKILL.md'), '# dev version\n')
    // Shipped skill under core/ai/skills/skill-creator — point at the real one via config
    mkdirSync(join(tmp, 'core', 'ai', 'skills', 'skill-creator'), { recursive: true })
    writeFileSync(
      join(tmp, 'core', 'ai', 'skills', 'skill-creator', 'SKILL.md'),
      '---\nname: skill-creator\ndescription: shipped\n---\n# shipped\n',
    )
    writeFileSync(
      join(tmp, 'core', 'ai', 'skills', 'tiers.json'),
      JSON.stringify({ default: ['core'], tiers: { core: { skills: ['skill-creator'] } } }),
    )
    writeFileSync(join(tmp, 'dev', 'framework.config.json'), JSON.stringify({ harnesses: ['test-harness'] }))
  })

  afterAll(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  test('dev skill symlink wins when name matches a shipped skill', () => {
    runDev(tmp)
    const entry = join(tmp, '.test', 'skills', 'skill-creator')
    expect(existsSync(entry)).toBe(true)
    expect(lstatSync(entry).isSymbolicLink(), 'dev skill should remain a symlink').toBe(true)
  })
})
